export const reconciliationUxVi = {
  title:'Đối soát thanh toán', subtitle:'Tra cứu khoản tiền, kiểm tra dữ kiện và mở đúng đơn để đối soát. Không tự ghép theo số tiền.',
  search:'Tìm ID nội bộ hoặc mã giao dịch', source:'Nguồn nhận', status:'Trạng thái', amount:'Số tiền chính xác', currency:'Đơn vị tiền', all:'Tất cả', apply:'Áp dụng bộ lọc', reset:'Xóa bộ lọc',
  unresolved:'Chưa ghép', observed:'Đã quan sát', review:'Cần đối soát', claimed:'Đã ghép', conflictsOnly:'Chỉ dữ kiện có xung đột',
  loading:'Đang tải khoản tiền…', empty:'Chưa có khoản tiền cần đối soát.', noResults:'Không có khoản tiền khớp bộ lọc.', error:'Không tải được danh sách đối soát.', retry:'Thử lại',
  internalId:'ID đối soát nội bộ', reference:'Mã giao dịch / TxID', receiver:'Nơi nhận', missingReceiver:'Chưa có dữ kiện nơi nhận', receivedAt:'Tiền được ghi nhận lúc', observedAt:'Hệ thống quan sát lúc',
  copyId:'Sao chép ID dùng trong Telegram', copyReference:'Sao chép mã giao dịch', copied:'Đã sao chép', copyFailed:'Không sao chép được. Hãy chọn và sao chép thủ công.',
  investigate:'Cần điều tra dữ kiện — không thể xác nhận tay', investigateHint:'Nguồn cung cấp trả dữ kiện không nhất quán. Không xóa trạng thái này hoặc gán lại khoản tiền để bỏ qua kiểm tra.',
  selectable:'Có thể chọn để yêu cầu đối soát', readonly:'Chỉ xem — không gán lại', unknownReason:'Cần kiểm tra dữ kiện của khoản tiền',
  reasons:{'ambiguous-order-or-deposit':'Nhiều đơn hoặc mã nạp cùng khớp','older-unresolved-instruction':'Còn chỉ dẫn thanh toán cũ chưa giải quyết','ambiguous-or-unmatched-memo':'Nội dung chuyển tiền chưa xác định được đích','receiver-not-provable':'Chưa xác minh được nơi nhận','provider-facts-changed':'Dữ kiện từ nguồn thanh toán thay đổi','missing-or-mismatched-receiver-snapshot':'Thiếu hoặc lệch thông tin nơi nhận đã chốt','wrong-receiver':'Không đúng nơi nhận','target-not-awaiting-payment':'Đích không còn chờ thanh toán','target-already-paid':'Đích đã được trả bằng khoản khác','deposit-not-awaiting-payment':'Mã nạp không còn chờ tiền'},
  sources:{'CRYPTO:BEP20':'USDT · BEP20','CRYPTO:TRC20':'USDT · TRC20',BINANCE_ID:'Chuyển Binance ID',SEPAY:'Chuyển khoản SePay',BINANCE_MERCHANT:'Binance Pay Merchant'},
  order:'Mã đơn cần đối soát', openOrder:'Mở đơn', orderHelp:'Mở chi tiết đơn và chọn rõ khoản tiền trong hộp xác nhận. Việc mở trang không ghi nhận thanh toán.',
  walletNotice:'Khoản nạp ví và xung đột dữ kiện chỉ tra cứu trong màn hình này. Không cộng ví hoặc gán người nhận khi chưa đủ bằng chứng.',
  listLabel:'Danh sách khoản tiền', choose:'Chọn khoản tiền', filterAmountError:'Nhập số không âm, tối đa 12 chữ số nguyên và 6 chữ số thập phân.',
  relatedOrder:'Đơn đã ghép', relatedDeposit:'Mã nạp đã ghép', count:(value:number)=>`${value} khoản tiền`,
};
export type ReconciliationUx = typeof reconciliationUxVi;
export const reconciliationUxEn: ReconciliationUx = {
  title:'Payment reconciliation',subtitle:'Find payments, inspect the evidence, and open the correct order. Amount alone never assigns a payment.',
  search:'Search internal ID or transaction reference',source:'Payment source',status:'Status',amount:'Exact amount',currency:'Currency',all:'All',apply:'Apply filters',reset:'Clear filters',
  unresolved:'Unassigned',observed:'Observed',review:'Needs review',claimed:'Assigned',conflictsOnly:'Conflicting evidence only',loading:'Loading payments…',empty:'No payments need reconciliation.',noResults:'No payments match these filters.',error:'Could not load payments.',retry:'Try again',
  internalId:'Internal reconciliation ID',reference:'Transaction reference / TxID',receiver:'Recipient',missingReceiver:'Recipient evidence unavailable',receivedAt:'Payment received',observedAt:'Observed by the store',copyId:'Copy ID for Telegram',copyReference:'Copy reference',copied:'Copied',copyFailed:'Could not copy. Select and copy the text manually.',
  investigate:'Investigate evidence — manual confirmation unavailable',investigateHint:'The provider returned conflicting facts. Do not clear this state or reassign the payment to bypass verification.',selectable:'Available to request reconciliation',readonly:'Read only — cannot reassign',unknownReason:'Payment evidence needs review',
  reasons:{'ambiguous-order-or-deposit':'Multiple orders or deposits match','older-unresolved-instruction':'An older payment instruction is unresolved','ambiguous-or-unmatched-memo':'The payment memo does not identify a target','receiver-not-provable':'Recipient has not been verified','provider-facts-changed':'Provider payment facts changed','missing-or-mismatched-receiver-snapshot':'Recipient snapshot is missing or differs','wrong-receiver':'Recipient does not match','target-not-awaiting-payment':'The target is no longer awaiting payment','target-already-paid':'The target was paid by another transfer','deposit-not-awaiting-payment':'The deposit is no longer awaiting payment'},
  sources:{'CRYPTO:BEP20':'USDT · BEP20','CRYPTO:TRC20':'USDT · TRC20',BINANCE_ID:'Binance ID transfer',SEPAY:'SePay bank transfer',BINANCE_MERCHANT:'Binance Pay Merchant'},
  order:'Order code to reconcile',openOrder:'Open order',orderHelp:'Open the order and explicitly select a payment in its confirmation dialog. Opening a page does not settle a payment.',walletNotice:'Wallet deposits and evidence conflicts are read-only here. Do not credit a wallet or assign a recipient without sufficient evidence.',listLabel:'Payments',choose:'Select payment',filterAmountError:'Enter a non-negative number with up to 12 integer and 6 decimal digits.',relatedOrder:'Assigned order',relatedDeposit:'Assigned deposit',count:(value:number)=>`${value} payments`,
};
export const reconciliationUxZh: ReconciliationUx = {
  title:'付款对账',subtitle:'查找付款、核实信息并打开正确订单。不会仅凭金额自动关联付款。',search:'搜索内部 ID 或交易编号',source:'收款来源',status:'状态',amount:'准确金额',currency:'币种',all:'全部',apply:'应用筛选',reset:'清除筛选',unresolved:'未关联',observed:'已观察',review:'待核实',claimed:'已关联',conflictsOnly:'仅显示信息冲突',loading:'正在加载付款…',empty:'目前没有待对账付款。',noResults:'没有符合筛选的付款。',error:'无法加载付款列表。',retry:'重试',internalId:'内部对账 ID',reference:'交易编号 / TxID',receiver:'收款方',missingReceiver:'尚无收款方信息',receivedAt:'到账时间',observedAt:'系统观察时间',copyId:'复制供 Telegram 使用的 ID',copyReference:'复制交易编号',copied:'已复制',copyFailed:'无法复制，请选择文本手动复制。',investigate:'需要调查信息，无法手动确认',investigateHint:'付款来源返回了冲突的信息。请勿清除状态或重新分配付款以绕过核实。',selectable:'可选择并申请对账',readonly:'仅查看，不可重新分配',unknownReason:'需要核实付款信息',
  reasons:{'ambiguous-order-or-deposit':'多个订单或充值记录符合条件','older-unresolved-instruction':'仍有较早的付款指引未解决','ambiguous-or-unmatched-memo':'付款备注未能确定目标','receiver-not-provable':'收款方尚未验证','provider-facts-changed':'付款来源信息发生变化','missing-or-mismatched-receiver-snapshot':'缺少收款快照或信息不一致','wrong-receiver':'收款方不符','target-not-awaiting-payment':'目标已不再等待付款','target-already-paid':'目标已由另一笔付款支付','deposit-not-awaiting-payment':'充值记录已不再等待付款'},sources:{'CRYPTO:BEP20':'USDT · BEP20','CRYPTO:TRC20':'USDT · TRC20',BINANCE_ID:'Binance ID 转账',SEPAY:'SePay 银行转账',BINANCE_MERCHANT:'Binance Pay 商户'},order:'需要对账的订单号',openOrder:'打开订单',orderHelp:'打开订单并在确认窗口中明确选择付款。打开页面不会确认付款。',walletNotice:'此页面仅查看充值及信息冲突。未取得足够证据前，不可增加余额或指定收款对象。',listLabel:'付款列表',choose:'选择付款',filterAmountError:'请输入非负数字，整数最多 12 位，小数最多 6 位。',relatedOrder:'关联订单',relatedDeposit:'关联充值',count:(value:number)=>`${value} 笔付款`,
};
