export const TELEGRAM_ADMIN_COPY = {
  review: ['Thao tác cần kiểm tra', 'Actions awaiting review', '待检查操作'],
  reviewed: ['Đã kiểm tra kết quả', 'Result reviewed', '已检查结果'],
  reviewConfirm: [
    'Đã kiểm tra đối tượng và nhật ký? Gỡ chặn không thực hiện lại thao tác.',
    'Checked the target and audit log? Acknowledging unlocks it without repeating the action.',
    '已检查目标和日志？确认仅解除阻止，不会重复操作。',
  ],
  product: ['Sản phẩm', 'Product', '商品'],
  variant: ['Loại sản phẩm', 'Option', '规格'],
  order: ['Đơn hàng', 'Order', '订单'],
  customer: ['Khách hàng', 'Customer', '客户'],
  coupon: ['Mã giảm giá', 'Coupon', '优惠码'],
  policy: ['Chính sách', 'Policy', '政策'],
  stockDrawMode: ['Cách rút kho', 'Stock draw order', '取库存顺序'],
  binancePayEnabled: [
    'Bật Binance Pay',
    'Enable Binance Pay',
    '启用 Binance Pay',
  ],
  binanceIdEnabled: ['Bật Binance ID', 'Enable Binance ID', '启用 Binance ID'],
  binanceId: [
    'Binance ID nhận tiền',
    'Receiving Binance ID',
    '收款 Binance ID',
  ],
  cryptoEnabled: ['Bật USDT on-chain', 'Enable on-chain USDT', '启用链上 USDT'],
  bep20Address: ['Địa chỉ BEP20', 'BEP20 address', 'BEP20 地址'],
  trc20Address: ['Địa chỉ TRC20', 'TRC20 address', 'TRC20 地址'],
  sepayEnabled: ['Bật ngân hàng', 'Enable bank transfer', '启用银行转账'],
  sepayBank: ['Ngân hàng', 'Bank', '银行'],
  sepayAccountNumber: [
    'Số tài khoản nhận tiền',
    'Receiving bank account',
    '收款银行账号',
  ],
  sepayAccountHolder: ['Chủ tài khoản', 'Account holder', '账户持有人'],
  sepayApiKey: ['Khóa SePay', 'SePay key', 'SePay 密钥'],
  sepayWebhookSecret: [
    'Khóa webhook SePay',
    'SePay webhook secret',
    'SePay webhook 密钥',
  ],
  vndPerUsdt: ['VND/USDT', 'VND/USDT', 'VND/USDT'],
  cnyPerUsdt: ['CNY/USDT', 'CNY/USDT', 'CNY/USDT'],
  rateAuto: ['Tự cập nhật tỉ giá', 'Automatic exchange rates', '自动更新汇率'],
  rateMarkupPercent: ['Biên tỉ giá (%)', 'Rate markup (%)', '汇率加价 (%)'],
  rateHour: ['Giờ cập nhật (0-23)', 'Update hour (0-23)', '更新时间 (0-23)'],
  supportChannels: [
    'Kênh hỗ trợ (JSON)',
    'Support channels (JSON)',
    '支持渠道 (JSON)',
  ],
  supportNote: ['Ghi chú hỗ trợ', 'Support note', '支持备注'],
  aiProvider: ['Nhà cung cấp AI', 'AI provider', 'AI 提供商'],
  aiBaseUrl: ['Địa chỉ API AI', 'AI API URL', 'AI API 地址'],
  aiModel: ['Model AI', 'AI model', 'AI 模型'],
  aiApiKey: ['Khóa API AI', 'AI API key', 'AI API 密钥'],
  telegramSendAnnouncement: [
    'Gửi thông báo khi bắt đầu',
    'Send start announcement',
    '启动时发送公告',
  ],
  telegramStockAlertsEnabled: [
    'Báo hàng mới cho khách',
    'Notify customers of restocks',
    '通知客户补货',
  ],
  telegramGreeting: ['Lời chào', 'Greeting', '问候语'],
  telegramOwnerChatId: [
    'Chat ID nhận cảnh báo',
    'Alert recipient Chat ID',
    '提醒接收 Chat ID',
  ],
  telegramOwnerOrderAlertsEnabled: [
    'Báo đơn mới',
    'New order alerts',
    '新订单提醒',
  ],
  telegramOwnerStuckAlertsEnabled: [
    'Báo đơn chờ lâu',
    'Stuck order alerts',
    '超时订单提醒',
  ],
  telegramOwnerStuckMinutes: [
    'Ngưỡng phút chờ',
    'Waiting threshold in minutes',
    '等待分钟数',
  ],
  telegramOwnerLowStockAlertsEnabled: [
    'Báo tồn thấp',
    'Low stock alerts',
    '低库存提醒',
  ],
  telegramOwnerLowStockThreshold: [
    'Ngưỡng tồn thấp',
    'Low stock threshold',
    '低库存阈值',
  ],
  title: ['Quản trị Telegram', 'Telegram Admin', 'Telegram 管理'],
  access: ['Quyền quản trị', 'Admin access', '管理权限'],
  enable: [
    'Bật quản trị qua Telegram',
    'Enable Telegram administration',
    '启用 Telegram 管理',
  ],
  name: ['Tên', 'Name', '名称'],
  permission: ['Quyền', 'Permission', '权限'],
  VIEWER: ['Chỉ xem', 'Read only', '只读'],
  OPERATOR: ['Vận hành', 'Operations', '运营'],
  FULL: ['Toàn quyền Telegram', 'Full Telegram access', 'Telegram 完整权限'],
  active: ['Đang bật', 'Enabled', '启用'],
  inactive: ['Đã tắt', 'Disabled', '禁用'],
  add: ['Thêm', 'Add', '添加'],
  edit: ['Sửa', 'Edit', '编辑'],
  save: ['Lưu', 'Save', '保存'],
  cancel: ['Hủy', 'Cancel', '取消'],
  remove: ['Xóa', 'Delete', '删除'],
  confirm: ['Xác nhận', 'Confirm', '确认'],
  back: ['Quay lại', 'Back', '返回'],
  refresh: ['Làm mới', 'Refresh', '刷新'],
  store: ['Về cửa hàng', 'Back to shop', '返回商店'],
  overview: ['Tổng quan', 'Overview', '概览'],
  orders: ['Đơn hàng', 'Orders', '订单'],
  products: ['Sản phẩm & kho', 'Products & stock', '商品与库存'],
  customers: ['Khách hàng', 'Customers', '客户'],
  coupons: ['Mã giảm giá', 'Coupons', '优惠码'],
  content: ['Nội dung', 'Content', '内容'],
  settings: ['Cài đặt', 'Settings', '设置'],
  audit: ['Nhật ký', 'Audit log', '操作日志'],
  search: ['Tìm kiếm', 'Search', '搜索'],
  all: ['Tất cả', 'All', '全部'],
  empty: ['Chưa có dữ liệu', 'No records', '暂无数据'],
  revenue: ['Doanh thu', 'Revenue', '营业额'],
  pending: ['Chờ thanh toán', 'Awaiting payment', '待付款'],
  stock: ['Kho hàng', 'Stock', '库存'],
  lowStock: ['Sắp hết hàng', 'Low stock', '库存不足'],
  import: ['Nhập kho', 'Import stock', '导入库存'],
  withdraw: ['Rút kho', 'Withdraw stock', '取出库存'],
  restore: ['Khôi phục', 'Restore', '恢复'],
  export: ['Xuất file', 'Export file', '导出文件'],
  keys: ['Xem key', 'View keys', '查看密钥'],
  variants: ['Loại sản phẩm', 'Options', '规格'],
  price: ['Giá', 'Price', '价格'],
  priceCurrency: ['Đơn vị tiền', 'Currency', '币种'],
  quantity: ['Số lượng', 'Quantity', '数量'],
  mode: ['Cách rút', 'Draw order', '取出顺序'],
  markPaid: ['Xác nhận nhận tiền', 'Confirm payment received', '确认收款'],
  redeliver: ['Giao bù', 'Retry delivery', '补发'],
  lock: ['Khóa khách', 'Lock customer', '锁定客户'],
  unlock: ['Mở khóa khách', 'Unlock customer', '解锁客户'],
  resetPassword: ['Đặt lại mật khẩu', 'Reset password', '重置密码'],
  translate: ['Dịch EN/ZH', 'Translate EN/ZH', '翻译 EN/ZH'],
  announcement: ['Thông báo', 'Announcement', '公告'],
  legal: ['Chính sách', 'Policies', '政策'],
  payments: ['Thanh toán', 'Payments', '支付'],
  rates: ['Tỉ giá', 'Exchange rates', '汇率'],
  support: ['Hỗ trợ', 'Support', '支持'],
  ai: ['AI dịch', 'Translation AI', 'AI 翻译'],
  alerts: ['Cảnh báo', 'Alerts', '提醒'],
  note: ['Ghi chú', 'Note', '备注'],
  titleField: ['Tiêu đề', 'Title', '标题'],
  body: ['Nội dung', 'Body', '正文'],
  category: ['Danh mục', 'Category', '分类'],
  description: ['Mô tả', 'Description', '描述'],
  shortDescription: ['Mô tả ngắn', 'Short description', '简短描述'],
  slug: ['Slug', 'Slug', 'Slug'],
  sortOrder: ['Thứ tự', 'Sort order', '排序'],
  code: ['Mã', 'Code', '代码'],
  type: ['Loại giảm giá', 'Discount type', '折扣类型'],
  value: ['Mức giảm', 'Discount value', '折扣值'],
  minAmount: [
    'Đơn tối thiểu (USDT)',
    'Minimum order (USDT)',
    '最低订单 (USDT)',
  ],
  maxUses: ['Tổng lượt dùng', 'Total uses allowed', '总使用次数'],
  perUserLimit: ['Lượt dùng mỗi khách', 'Uses per customer', '每位客户次数'],
  startsAt: ['Bắt đầu (ISO)', 'Starts at (ISO)', '开始时间 (ISO)'],
  expiresAt: ['Hết hạn (ISO)', 'Expires at (ISO)', '到期时间 (ISO)'],
  lastSeen: ['Truy cập gần nhất', 'Last access', '最近访问'],
  preview: ['Xem trước', 'Preview', '预览'],
  customerMode: ['Khách', 'Customer', '客户'],
  adminMode: ['Admin', 'Admin', '管理'],
  forbidden: [
    'Bạn không có quyền thực hiện thao tác này.',
    'You do not have permission for this action.',
    '您没有权限执行此操作。',
  ],
  expired: [
    'Phiên thao tác đã hết hạn. Mở lại /admin.',
    'This action expired. Open /admin again.',
    '操作已过期，请重新打开 /admin。',
  ],
  changed: [
    'Dữ liệu đã thay đổi. Vui lòng mở lại thao tác.',
    'Data changed. Please reopen the action.',
    '数据已变更，请重新打开操作。',
  ],
  saved: ['Đã lưu', 'Saved', '已保存'],
  done: ['Đã thực hiện', 'Completed', '已完成'],
  processing: [
    'Đang xử lý hoặc cần kiểm tra nhật ký; không thực hiện lại.',
    'Processing or awaiting review; not repeated.',
    '正在处理或等待检查，不会重复执行。',
  ],
  invalid: ['Giá trị không hợp lệ.', 'Invalid value.', '值无效。'],
  input: ['Nhập giá trị', 'Enter a value', '请输入值'],
  verifyTarget: [
    'Nhập lại mã đối tượng để tiếp tục',
    'Retype the target code to continue',
    '再次输入目标代码以继续',
  ],
  importHint: [
    'Gửi text, file .json hoặc .txt (tối đa 1 MB, 1.000 món).',
    'Send text, .json or .txt (maximum 1 MB, 1,000 items).',
    '发送文本、.json 或 .txt（最多 1 MB、1,000 项）。',
  ],
  clear: ['Xóa giá trị', 'Clear value', '清空值'],
  skip: ['Giữ nguyên', 'Keep current', '保持不变'],
  count: ['Số món', 'Items', '项目数'],
  before: ['Hiện tại', 'Current', '当前'],
  after: ['Thay đổi', 'Changes', '更改'],
  masked: ['Đã che', 'Hidden', '已隐藏'],
  removeConfirm: [
    'Thu hồi quyền của ID này?',
    'Revoke access for this ID?',
    '撤销此 ID 的权限？',
  ],
  webOnly: [
    'Chỉ chủ cửa hàng quản lý quyền trên web.',
    'Only the store owner manages access on the web.',
    '仅店主可在网页上管理权限。',
  ],
  testOnly: [
    'Đã mô phỏng; dữ liệu cửa hàng không thay đổi.',
    'Simulated; store data is unchanged.',
    '已模拟，商店数据未更改。',
  ],
  error: [
    'Có lỗi. Vui lòng thử lại.',
    'Something went wrong. Please retry.',
    '发生错误，请重试。',
  ],
} as const;
export type TelegramAdminTextKey = keyof typeof TELEGRAM_ADMIN_COPY;
export function telegramAdminText(
  lang: 'vi' | 'en' | 'zh',
  key: TelegramAdminTextKey,
): string {
  return TELEGRAM_ADMIN_COPY[key][lang === 'en' ? 1 : lang === 'zh' ? 2 : 0];
}
